export const CREATE_POST = "CREATE_POST"
export const GET_POSTS = "GET_POSTS"
export const UPDATE_POST = "UPDATE_POST"
export const DELETE_POST = "DELETE_POST"
export const LIKE_POST = "LIKE_POST"
export const REGISTER = "REGISTER" 
export const LOGIN = "LOGIN_USER"
export const LOGOUT = "LOGOUT_USER"
