export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST"
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS"
export const GET_ALL_POSTS_FAIL = "GET_ALL_POSTS_FAIL"



export const CREATE_A_POST_REQUEST = "CREATE_A_POST_REQUEST"
export const CREATE_A_POST_SUCCESS = "CREATE_A_POST_SUCCESS"
export const CREATE_A_POST_FAIL = "CREATE_A_POST_FAIL"



export const UPDATE_A_POST_REQUEST = "UPDATE_A_POST_REQUEST"
export const UPDATE_A_POST_SUCCESS = "UPDATE_A_POST_SUCCESS"
export const UPDATE_A_POST_FAIL = "UPDATE_A_POST_FAIL"



export const DELETE_A_POST_REQUEST = "DELETE_A_POST_REQUEST"
export const DELETE_A_POST_SUCCESS = "DELETE_A_POST_SUCCESS"
export const DELETE_A_POST_FAIL = "DELETE_A_POST_FAIL"



export const LIKE_A_POST_REQUEST = "LIKE_A_POST_REQUEST"
export const LIKE_A_POST_SUCCESS = "LIKE_A_POST_SUCCESS"
export const LIKE_A_POST_FAIL = "LIKE_A_POST_FAIL"



export const UNLIKE_A_POST_REQUEST = "UNLIKE_A_POST_REQUEST"
export const UNLIKE_A_POST_SUCCESS = "UNLIKE_A_POST_SUCCESS"
export const UNLIKE_A_POST_FAIL = "UNLIKE_A_POST_FAIL"